channels:
- conda-forge
dependencies:
- python=3.7
- pip:
  - azureml-core==1.27.0
  - azureml-defaults==1.27.0
  - joblib
  - scikit-learn==0.22.1
  - xgboost==1.1.1
name: azureml_709dece87a24630cbe52e93d5b99aed6
